site_name: andock-ci pipeline Documentation
theme: readthedocs
repo_url: https://github.com/andock-ci/pipeline
site_url: https://docs.andock-ci
markdown_extensions:
  - markdown.extensions.admonition
pages:
  - Home: index.md
  - Getting started:
    - What is this software for: getting-started/the-software.md
    - System requirements: getting-started/system-requirements.md
    - Docksal addon: getting-started/docksal.md
    - Automate on your ci: getting-started/ci.md
  - Configuration:
    - Overview: configuration/overview.md
    - Hook configurations:
      - Drupal: configuration/example-drupal-hooks.md
    - Build configuration: configuration/build.md
    - Fin configuration: configuration/fin.md
    - Server configuration: configuration/fin.md